server:
  port: 9090
spring:
  datasource:
    username: root
    password: nopass
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.213.104:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false

