server:
  port: 8080
spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://192.168.213.104:3306/test
      username: yatu
      password: nopass
      driver-class-name: com.mysql.jdbc.Driver
    slave:
      jdbc-url: jdbc:mysql://192.168.213.105:3306/test
      username: yatu
      password: nopass
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true